--
-- PostgreSQL database dump
--

\restrict 2t1WgNC9Uy21UwZ5g4lFcmX79ixf5qT3vKLT7Y6x1Fyabcnrg1TslofUIdIiB8r

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: album; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.album (
    id bigint NOT NULL,
    cover_url character varying(500),
    release_year integer,
    title character varying(180) NOT NULL,
    artist_id bigint NOT NULL
);


ALTER TABLE public.album OWNER TO postgres;

--
-- Name: album_genre; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.album_genre (
    album_id bigint NOT NULL,
    genre_id bigint NOT NULL
);


ALTER TABLE public.album_genre OWNER TO postgres;

--
-- Name: album_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.album ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.album_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    avatar_content_type character varying(255),
    avatar_image bytea,
    bio character varying(300),
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: artist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.artist (
    id bigint NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.artist OWNER TO postgres;

--
-- Name: artist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.artist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.artist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: genre; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.genre (
    id bigint NOT NULL,
    name character varying(80) NOT NULL
);


ALTER TABLE public.genre OWNER TO postgres;

--
-- Name: genre_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.genre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: music_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.music_item (
    id bigint NOT NULL,
    artist character varying(150) NOT NULL,
    item_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(180) NOT NULL,
    catalog_album_id bigint,
    catalog_track_id bigint,
    section_id bigint NOT NULL,
    CONSTRAINT music_item_item_type_check CHECK (((item_type)::text = ANY ((ARRAY['TRACK'::character varying, 'ALBUM'::character varying])::text[]))),
    CONSTRAINT music_item_status_check CHECK (((status)::text = ANY ((ARRAY['TO_LISTEN'::character varying, 'LISTENED'::character varying])::text[])))
);


ALTER TABLE public.music_item OWNER TO postgres;

--
-- Name: music_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.music_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.music_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: music_section; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.music_section (
    id bigint NOT NULL,
    name character varying(80) NOT NULL,
    note_color character varying(20),
    wall_id bigint NOT NULL
);


ALTER TABLE public.music_section OWNER TO postgres;

--
-- Name: music_section_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.music_section ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.music_section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: music_wall; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.music_wall (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    wall_color character varying(7),
    wallpaper character varying(20),
    owner_id bigint NOT NULL,
    CONSTRAINT music_wall_wallpaper_check CHECK (((wallpaper)::text = ANY ((ARRAY['NONE'::character varying, 'IMAGE_1'::character varying, 'IMAGE_2'::character varying, 'IMAGE_3'::character varying, 'IMAGE_4'::character varying, 'IMAGE_5'::character varying, 'IMAGE_6'::character varying, 'IMAGE_7'::character varying, 'IMAGE_8'::character varying, 'IMAGE_9'::character varying])::text[])))
);


ALTER TABLE public.music_wall OWNER TO postgres;

--
-- Name: music_wall_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.music_wall ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.music_wall_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: track; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.track (
    id bigint NOT NULL,
    duration_seconds integer,
    title character varying(180) NOT NULL,
    album_id bigint,
    artist_id bigint NOT NULL
);


ALTER TABLE public.track OWNER TO postgres;

--
-- Name: track_genre; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.track_genre (
    track_id bigint NOT NULL,
    genre_id bigint NOT NULL
);


ALTER TABLE public.track_genre OWNER TO postgres;

--
-- Name: track_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.track ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.track_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wall_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wall_members (
    wall_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.wall_members OWNER TO postgres;

--
-- Name: album album_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album
    ADD CONSTRAINT album_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: artist artist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.artist
    ADD CONSTRAINT artist_pkey PRIMARY KEY (id);


--
-- Name: genre genre_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genre
    ADD CONSTRAINT genre_pkey PRIMARY KEY (id);


--
-- Name: music_item music_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.music_item
    ADD CONSTRAINT music_item_pkey PRIMARY KEY (id);


--
-- Name: music_section music_section_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.music_section
    ADD CONSTRAINT music_section_pkey PRIMARY KEY (id);


--
-- Name: music_wall music_wall_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.music_wall
    ADD CONSTRAINT music_wall_pkey PRIMARY KEY (id);


--
-- Name: track_genre track_genre_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.track_genre
    ADD CONSTRAINT track_genre_pkey PRIMARY KEY (track_id, genre_id);


--
-- Name: track track_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.track
    ADD CONSTRAINT track_pkey PRIMARY KEY (id);


--
-- Name: app_user uk3k4cplvh82srueuttfkwnylq0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk3k4cplvh82srueuttfkwnylq0 UNIQUE (username);


--
-- Name: album uk_album_artist_title; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album
    ADD CONSTRAINT uk_album_artist_title UNIQUE (artist_id, title);


--
-- Name: album_genre uk_album_genre; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album_genre
    ADD CONSTRAINT uk_album_genre PRIMARY KEY (album_id, genre_id);


--
-- Name: artist uk_artist_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.artist
    ADD CONSTRAINT uk_artist_name UNIQUE (name);


--
-- Name: genre uk_genre_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genre
    ADD CONSTRAINT uk_genre_name UNIQUE (name);


--
-- Name: wall_members wall_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wall_members
    ADD CONSTRAINT wall_members_pkey PRIMARY KEY (wall_id, user_id);


--
-- Name: idx_album_title_trgm; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_album_title_trgm ON public.album USING gin (lower((title)::text) public.gin_trgm_ops);


--
-- Name: idx_artist_name_trgm; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_artist_name_trgm ON public.artist USING gin (lower((name)::text) public.gin_trgm_ops);


--
-- Name: idx_track_title_trgm; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_track_title_trgm ON public.track USING gin (lower((title)::text) public.gin_trgm_ops);


--
-- Name: music_wall fk4v9ryrcu2jq33soqkon4ce8y5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.music_wall
    ADD CONSTRAINT fk4v9ryrcu2jq33soqkon4ce8y5 FOREIGN KEY (owner_id) REFERENCES public.app_user(id);


--
-- Name: music_item fk5quiikbjj8k51klrs9oaefixr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.music_item
    ADD CONSTRAINT fk5quiikbjj8k51klrs9oaefixr FOREIGN KEY (catalog_album_id) REFERENCES public.album(id);


--
-- Name: track_genre fk7fk536dvv5u9jobhp0wtcbfal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.track_genre
    ADD CONSTRAINT fk7fk536dvv5u9jobhp0wtcbfal FOREIGN KEY (genre_id) REFERENCES public.genre(id);


--
-- Name: wall_members fkanjlpxh3woomkmjv56avw9qcf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wall_members
    ADD CONSTRAINT fkanjlpxh3woomkmjv56avw9qcf FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: track fkaxm9pbgk7ptorfyk3o6911q05; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.track
    ADD CONSTRAINT fkaxm9pbgk7ptorfyk3o6911q05 FOREIGN KEY (album_id) REFERENCES public.album(id);


--
-- Name: track_genre fkboa4jxp2d7bagmrurr3m063pw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.track_genre
    ADD CONSTRAINT fkboa4jxp2d7bagmrurr3m063pw FOREIGN KEY (track_id) REFERENCES public.track(id);


--
-- Name: album_genre fkgobybiodeygwcmlhr7sxv4y01; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album_genre
    ADD CONSTRAINT fkgobybiodeygwcmlhr7sxv4y01 FOREIGN KEY (album_id) REFERENCES public.album(id);


--
-- Name: music_section fkh0jyhi45mj23y0erkghc80u16; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.music_section
    ADD CONSTRAINT fkh0jyhi45mj23y0erkghc80u16 FOREIGN KEY (wall_id) REFERENCES public.music_wall(id);


--
-- Name: track fki28jadqiuqk1dlxtl0me7hqh2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.track
    ADD CONSTRAINT fki28jadqiuqk1dlxtl0me7hqh2 FOREIGN KEY (artist_id) REFERENCES public.artist(id);


--
-- Name: music_item fkio5mkbtu0up4lujn1378au98j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.music_item
    ADD CONSTRAINT fkio5mkbtu0up4lujn1378au98j FOREIGN KEY (section_id) REFERENCES public.music_section(id);


--
-- Name: album_genre fkld60pu9t8ff70bc6nrnnv91lx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album_genre
    ADD CONSTRAINT fkld60pu9t8ff70bc6nrnnv91lx FOREIGN KEY (genre_id) REFERENCES public.genre(id);


--
-- Name: music_item fkmmqacjaup944dqe3wuw85u4m8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.music_item
    ADD CONSTRAINT fkmmqacjaup944dqe3wuw85u4m8 FOREIGN KEY (catalog_track_id) REFERENCES public.track(id);


--
-- Name: album fkmwc4fyyxb6tfi0qba26gcf8s1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album
    ADD CONSTRAINT fkmwc4fyyxb6tfi0qba26gcf8s1 FOREIGN KEY (artist_id) REFERENCES public.artist(id);


--
-- Name: wall_members fktbu4udnko8pjm1fj05ys5nqec; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wall_members
    ADD CONSTRAINT fktbu4udnko8pjm1fj05ys5nqec FOREIGN KEY (wall_id) REFERENCES public.music_wall(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 2t1WgNC9Uy21UwZ5g4lFcmX79ixf5qT3vKLT7Y6x1Fyabcnrg1TslofUIdIiB8r


